2022-09-09 09:09:32 jdbc[13]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'' (USERS: ""ID"" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."USERS"("ROLE","ID","EMAIL","PASSWORD","USERNAME","FIRST_NAME","GENDER","LAST_NAME","ABOUT","COMPANY_NAME")VALUES(?,?,?,?,?,?,?,?,?,?) [22018-214]
2022-09-09 09:09:32 jdbc[13]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'' (USERS: ""ID"" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."USERS"("ROLE","ID","EMAIL","PASSWORD","USERNAME","FIRST_NAME","GENDER","LAST_NAME","ABOUT","COMPANY_NAME")VALUES(?,?,?,?,?,?,?,?,?,?) [22018-214]
2022-09-09 09:09:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'' (USERS: ""ID"" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."USERS"("ROLE","ID","EMAIL","PASSWORD","USERNAME","FIRST_NAME","GENDER","LAST_NAME","ABOUT","COMPANY_NAME")VALUES(?,?,?,?,?,?,?,?,?,?) [22018-214]
2022-09-09 09:09:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'' (USERS: ""ID"" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."USERS"("ROLE","ID","EMAIL","PASSWORD","USERNAME","FIRST_NAME","GENDER","LAST_NAME","ABOUT","COMPANY_NAME")VALUES(?,?,?,?,?,?,?,?,?,?) [22018-214]
2022-09-09 09:10:18 jdbc[14]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'Male' (USERS: ""GENDER"" INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."USERS"("ROLE","ID","EMAIL","PASSWORD","USERNAME","FIRST_NAME","GENDER","LAST_NAME","ABOUT","COMPANY_NAME")VALUES(?,?,?,?,?,?,?,?,?,?) [22018-214]
2022-09-09 09:10:18 jdbc[14]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'Male' (USERS: ""GENDER"" INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."USERS"("ROLE","ID","EMAIL","PASSWORD","USERNAME","FIRST_NAME","GENDER","LAST_NAME","ABOUT","COMPANY_NAME")VALUES(?,?,?,?,?,?,?,?,?,?) [22018-214]
2022-09-09 09:12:19 jdbc[3]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-214]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 17 more
2022-09-09 15:30:47 jdbc[3]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-214]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 17 more
